[build]
# Default build command.
command = "npm run build"
publish = "public/"

[[redirects]]
force = true
from = "/docs/*"
status = 200
to = "https://docs.samelogic.com/:splat"

[context.production.environment]
NODE_VERSION = "14.17.4"

[context.deploy-preview.environment]
NODE_VERSION = "14.17.4"
