version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:latest
    working_directory: ~/samelogic-landing

  workspace_root: &workspace_root
    ~/samelogic-landing
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: yarn
      - run: yarn deploy
      - save_cache:
          key: sl-landing-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/*
  deploy:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          key: sl-landing-{{ checksum "yarn.lock" }}
      - run: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y python-dev python-pip
            sudo pip install awscli --upgrade
      - deploy:
          name: Deploy to S3
          command: aws s3 sync dist/ s3://www.samelogic.com/ --delete
      - deploy:
          name: Invalidate CloudFront cache
          command: aws cloudfront create-invalidation --distribution-id=E2HY12PGZTG471 --paths "/*"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
